### ISSUE TITLE
2nd Code Refactoring

### ISSUE THREAD

**Issue by hustle-dev** [hustle-dev/JS-Pair-Programming#10]
- [x] 1 Toggle side nav
- [x] 2 Scrolling goto top
- [x] 3 Counter
- [x] 4 Analog Clock
- [x] 5 Stopwatch
- [x] 6 Dark mode
- [x] 7 Popup
- [x] 8 Tabs
- [x] 9 Accordion
- [x] 10 Toaster
- [x] 11 Carousel slider
- [x] 12 Calendar & Datepicker
- [x] 13 Form validation

**Comment by sosoYim** [comment]
### 03 Counter 
- 고민 : 이벤트를 부여할 요소로 컨테이너를 잡을지, 각각의 버튼 요소에 잡을까?
- [case1] 컨테이너 : 코드를 효율적으로 작성, 클릭 이벤트에 대한 응집도 상승
- [case2] 각각의 버튼 : 가독성
- 결론[case2] : 버튼의 수가 2개 뿐인 간단한 컴포넌트이기 때문에 버튼간의 응집도 보다 가독성을 올리는 쪽으로 선택하였다.

**Comment by sosoYim** [comment]
### 05 Stopwatch
- 고민1: 버튼 이름
- [case1] startOrStop, resetOrLap : 버튼이 작동될 이름을 직접적으로 명시. 각각의 버튼이 어떤 버튼인지 직관적이고 구체적으로 알 수 있다.
- [case2] controlAction, controlRecord : 클래스 이름 control + 진행을 통제하거나 기록을 통제하는 버튼의 역할을 기준으로 작명
- 결론 [case1] : 보다 직관적인 버튼 이름으로 선택
---
- 고민2 : state (initial, ing, pause) 객체로 관리 {INITIAL: 'initial', ING:'ing', PAUSE:'pause'}
- [case1] 객체로 관리하지 않는다 : 각각의 상태를 코드에 직접 명시하여 간결하고 짧은 코드를 작성할 수 있다.
- [case2] 객체로 관리한다 : 값의 변동이 있을 경우 젹용을 한 번에 할 수 있고, 잘못된 상태값을 코드에서 사용하였을 때 생길 오류를 방지할 수 있다.
- 결론 [case2] : 유지보수 이슈가 크리티컬하다고 생각해서 case2 선택
---
- 함수 이름 변경
- ingLap -> appendLap
- timerStart -> startTimer
- pauseReset -> resetAll

**Comment by sosoYim** [comment]
### 08 Tabs
- 탭 요소에 해당하는 fragment 요소를 반환해주는 함수를 분리한다 vs 안한다
- [case1] createTapsFragment(data) 로 분리 : 함수의 역할을 나누고 가독성을 증진시킬 수 있다. 반면, 기존에 재사용하던 nav 돔 요소를 재사용할 수 없다.
- [case2] fetxhTabsData 안에서 한꺼번에 처리 : nav 돔요소를 재사용 할 수 있다. 로직이 한 곳에 다 들어있어 한 눈에 알아보기 힘들다.
- 결론 [case1] : 분리!
